% ========== Acreditar
perfs = [...
porder('01');...
porder('bb1');...
porder('0A');...
porder('b1');...
porder('t1t');...
porder('010');...
porder('b10');...
porder('001');...
porder('dd1');...
porder('t10');...
porder('A0')];
