% ********** Sequenza IX (Berio) - Paradigmatic 4 (Seq9-Parad4)
perfs = [   porder('t01'),...
            porder('t1'),...
            porder('d01'),...
            porder('d10'),...
            porder('001'),...
            porder('00I'),...
            porder('0t1'),...
            porder('tt1'),...
            porder('dd1'),...
            porder('bt1'),...
            porder('dt1'),...
            porder('a01'),...
            porder('id1'),...
            porder('0b1'),...
            porder('bb1'),...
            porder('0i1'),...
            porder('d01'),...
            porder('td1'),...
            porder('b01'),...
            porder('d1')];