% ========== Nets with properties similar to Minueto G (Anna Magdalena
% Bach) - see Rocha, 2023.

perfs = [porder('010'), porder('001'), porder('t01'), porder('tt1'),...
     porder('bt1'), porder('it1'), porder('0t1'), porder('t1'),...
     porder('01')];

% perfs = [porder('10'), porder('010'), porder('0T0'), porder('0B0'),...
%     porder('iB0'), porder('iI0'), porder('0I0'), porder('0I'),...
%     porder('01')];

% perfs = [porder('100'), porder('1t0'), porder('1b0'), porder('1bi'),...
%     porder('1ba'), porder('1ta'), porder('1ti'), porder('1tt'),...
%     porder('10t')];

% perfs = [porder('100'), porder('1t0'), porder('1b0'), porder('1bi'),...
%     porder('1ba'), porder('1ta'), porder('1ti'), porder('1tt'),...
%     porder('10t')];